var _add_blocked_term_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Moderation.BlockedTerms.AddBlockedTermResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_blocked_terms_1_1_add_blocked_term_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_blocked_terms_1_1_add_blocked_term_response" ]
];