var _automod_caught_message_2_automod_caught_message_8cs =
[
    [ "TwitchLib.PubSub.Models.Responses.Messages.AutomodCaughtMessage.AutomodCaughtMessage", "class_twitch_lib_1_1_pub_sub_1_1_models_1_1_responses_1_1_messages_1_1_automod_caught_message_1_1_automod_caught_message.html", "class_twitch_lib_1_1_pub_sub_1_1_models_1_1_responses_1_1_messages_1_1_automod_caught_message_1_1_automod_caught_message" ]
];