var _channel_subscription_gift_handler_8cs =
[
    [ "TwitchLib.EventSub.Websockets.Handler.Channel.Subscription.ChannelSubscriptionGiftHandler", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_subscription_1_1_channel_subscription_gift_handler.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_subscription_1_1_channel_subscription_gift_handler" ]
];