var _chat_settings_response_model_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Chat.ChatSettings.ChatSettingsResponseModel", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_chat_settings_1_1_chat_settings_response_model.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_chat_settings_1_1_chat_settings_response_model" ]
];