var _channel_moderator_remove_handler_8cs =
[
    [ "TwitchLib.EventSub.Websockets.Handler.Channel.Moderators.ChannelModeratorRemoveHandler", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_moderators_1_1_channel_moderator_remove_handler.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_moderators_1_1_channel_moderator_remove_handler" ]
];