var _channel_poll_begin_handler_8cs =
[
    [ "TwitchLib.EventSub.Websockets.Handler.Channel.Polls.ChannelPollBeginHandler", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_polls_1_1_channel_poll_begin_handler.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_polls_1_1_channel_poll_begin_handler" ]
];