var _channel_information_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Channels.GetChannelInformation.ChannelInformation", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_information_1_1_channel_information.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_information_1_1_channel_information" ]
];