var _channel_goal_end_handler_8cs =
[
    [ "TwitchLib.EventSub.Websockets.Handler.Channel.Goals.ChannelGoalEndHandler", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_goals_1_1_channel_goal_end_handler.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_goals_1_1_channel_goal_end_handler" ]
];