var _check_auto_mod_status_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Moderation.CheckAutoModStatus.CheckAutoModStatusResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_check_auto_mod_status_1_1_check_auto_mod_status_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_check_auto_mod_status_1_1_check_auto_mod_status_response" ]
];