var _create_stream_marker_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Streams.CreateStreamMarker.CreateStreamMarkerResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_streams_1_1_create_stream_marker_1_1_create_stream_marker_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_streams_1_1_create_stream_marker_1_1_create_stream_marker_response" ]
];