var _event_sub_websocket_session_info_message_8cs =
[
    [ "TwitchLib.EventSub.Websockets.Core.Models.EventSubWebsocketSessionInfoMessage", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_models_1_1_event_sub_websocket_session_info_message.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_models_1_1_event_sub_websocket_session_info_message" ]
];