var _event_sub_websocket_session_info_8cs =
[
    [ "TwitchLib.EventSub.Websockets.Core.Models.EventSubWebsocketSessionInfo", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_models_1_1_event_sub_websocket_session_info.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_models_1_1_event_sub_websocket_session_info" ]
];