var _get_moderator_events_2_event_data_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Moderation.GetModeratorEvents.EventData", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_get_moderator_events_1_1_event_data.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_get_moderator_events_1_1_event_data" ]
];