var _get_chat_settings_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Chat.ChatSettings.GetChatSettingsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_chat_settings_1_1_get_chat_settings_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_chat_settings_1_1_get_chat_settings_response" ]
];