var _get_channel_v_i_ps_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Channels.GetChannelVIPs.GetChannelVIPsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_v_i_ps_1_1_get_channel_v_i_ps_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_v_i_ps_1_1_get_channel_v_i_ps_response" ]
];