var _get_stream_tags_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Streams.GetStreamTags.GetStreamTagsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_streams_1_1_get_stream_tags_1_1_get_stream_tags_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_streams_1_1_get_stream_tags_1_1_get_stream_tags_response" ]
];