var _get_event_sub_subscriptions_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.EventSub.GetEventSubSubscriptionsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_event_sub_1_1_get_event_sub_subscriptions_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_event_sub_1_1_get_event_sub_subscriptions_response" ]
];