var _get_current_track_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Soundtrack.GetCurrentTrack.GetCurrentTrackResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_soundtrack_1_1_get_current_track_1_1_get_current_track_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_soundtrack_1_1_get_current_track_1_1_get_current_track_response" ]
];