var _get_banned_events_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Moderation.GetBannedEvents.GetBannedEventsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_get_banned_events_1_1_get_banned_events_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_get_banned_events_1_1_get_banned_events_response" ]
];