var _get_extension_transactions_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Extensions.Transactions.GetExtensionTransactionsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_extensions_1_1_transactions_1_1_get_extension_transactions_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_extensions_1_1_transactions_1_1_get_extension_transactions_response" ]
];