var _get_channel_editors_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Channels.GetChannelEditors.GetChannelEditorsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_editors_1_1_get_channel_editors_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_editors_1_1_get_channel_editors_response" ]
];