var _get_user_chat_color_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Chat.GetUserChatColor.GetUserChatColorResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_get_user_chat_color_1_1_get_user_chat_color_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_get_user_chat_color_1_1_get_user_chat_color_response" ]
];