var _get_code_status_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Entitlements.GetCodeStatus.GetCodeStatusResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_get_code_status_1_1_get_code_status_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_get_code_status_1_1_get_code_status_response" ]
];