var _get_channel_information_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Channels.GetChannelInformation.GetChannelInformationResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_information_1_1_get_channel_information_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_information_1_1_get_channel_information_response" ]
];