var _get_channel_emotes_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Chat.Emotes.GetChannelEmotes.GetChannelEmotesResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_emotes_1_1_get_channel_emotes_1_1_get_channel_emotes_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_emotes_1_1_get_channel_emotes_1_1_get_channel_emotes_response" ]
];