var _get_extension_analytics_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Analytics.GetExtensionAnalyticsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_analytics_1_1_get_extension_analytics_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_analytics_1_1_get_extension_analytics_response" ]
];