var _get_user_subscriptions_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Subscriptions.GetUserSubscriptionsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_subscriptions_1_1_get_user_subscriptions_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_subscriptions_1_1_get_user_subscriptions_response" ]
];