var _get_playlists_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Soundtrack.GetPlaylists.GetPlaylistsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_soundtrack_1_1_get_playlists_1_1_get_playlists_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_soundtrack_1_1_get_playlists_1_1_get_playlists_response" ]
];