var _get_broadcaster_subscription_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Subscriptions.GetBroadcasterSubscriptionsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_subscriptions_1_1_get_broadcaster_subscriptions_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_subscriptions_1_1_get_broadcaster_subscriptions_response" ]
];