var _get_extension_bits_products_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Bits.ExtensionBitsProducts.GetExtensionBitsProductsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_bits_1_1_extension_bits_products_1_1_get_extension_bits_products_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_bits_1_1_extension_bits_products_1_1_get_extension_bits_products_response" ]
];