var _live_stream_monitor_service_tests_8cs =
[
    [ "TwitchLib.Api.Test.Services.LiveStreamMonitorServiceTests", "class_twitch_lib_1_1_api_1_1_test_1_1_services_1_1_live_stream_monitor_service_tests.html", "class_twitch_lib_1_1_api_1_1_test_1_1_services_1_1_live_stream_monitor_service_tests" ],
    [ "TwitchLib.Api.Test.Services.LiveStreamMonitorServiceTests.Functionality", "class_twitch_lib_1_1_api_1_1_test_1_1_services_1_1_live_stream_monitor_service_tests_1_1_functionality.html", "class_twitch_lib_1_1_api_1_1_test_1_1_services_1_1_live_stream_monitor_service_tests_1_1_functionality" ],
    [ "TwitchLib.Api.Test.Services.LiveStreamMonitorServiceTests.Exceptions", "class_twitch_lib_1_1_api_1_1_test_1_1_services_1_1_live_stream_monitor_service_tests_1_1_exceptions.html", "class_twitch_lib_1_1_api_1_1_test_1_1_services_1_1_live_stream_monitor_service_tests_1_1_exceptions" ]
];