var _on_failure_to_receive_join_confirmation_args_8cs =
[
    [ "TwitchLib.Client.Events.OnFailureToReceiveJoinConfirmationArgs", "class_twitch_lib_1_1_client_1_1_events_1_1_on_failure_to_receive_join_confirmation_args.html", "class_twitch_lib_1_1_client_1_1_events_1_1_on_failure_to_receive_join_confirmation_args" ]
];