var _persistent_count_by_interval_awaitable_constraint_8cs =
[
    [ "TwitchLib.Api.Core.RateLimiter.PersistentCountByIntervalAwaitableConstraint", "class_twitch_lib_1_1_api_1_1_core_1_1_rate_limiter_1_1_persistent_count_by_interval_awaitable_constraint.html", "class_twitch_lib_1_1_api_1_1_core_1_1_rate_limiter_1_1_persistent_count_by_interval_awaitable_constraint" ]
];