var _twitch_lib_8_api_2_twitch_lib_8_api_8_helix_8_models_2_event_sub_2_event_sub_transport_8cs =
[
    [ "TwitchLib.Api.Helix.Models.EventSub.EventSubTransport", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_event_sub_1_1_event_sub_transport.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_event_sub_1_1_event_sub_transport" ]
];