var _twitch_lib_8_event_sub_8_websockets_8_example_2_websocket_hosted_service_8cs =
[
    [ "TwitchLib.EventSub.Websockets.Example.WebsocketHostedService", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_example_1_1_websocket_hosted_service.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_example_1_1_websocket_hosted_service" ]
];