var _update_automod_settings_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Moderation.AutomodSettings.UpdateAutomodSettingsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_automod_settings_1_1_update_automod_settings_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_automod_settings_1_1_update_automod_settings_response" ]
];