var _update_extension_bits_product_response_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Bits.ExtensionBitsProducts.UpdateExtensionBitsProductResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_bits_1_1_extension_bits_products_1_1_update_extension_bits_product_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_bits_1_1_extension_bits_products_1_1_update_extension_bits_product_response" ]
];