var _update_user_extensions_request_8cs =
[
    [ "TwitchLib.Api.Helix.Models.Users.UpdateUserExtensions.UpdateUserExtensionsRequest", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_users_1_1_update_user_extensions_1_1_update_user_extensions_request.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_users_1_1_update_user_extensions_1_1_update_user_extensions_request" ]
];