var _websocket_disconnected_args_8cs =
[
    [ "TwitchLib.EventSub.Websockets.Core.EventArgs.WebsocketDisconnectedArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_websocket_disconnected_args.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_websocket_disconnected_args" ]
];