var dir_41c02cec5a1f2b96f6eb161b76f6bf99 =
[
    [ "Ads.cs", "_ads_8cs.html", "_ads_8cs" ],
    [ "Analytics.cs", "_analytics_8cs.html", "_analytics_8cs" ],
    [ "Bits.cs", "_bits_8cs.html", "_bits_8cs" ],
    [ "ChannelPoints.cs", "_channel_points_8cs.html", "_channel_points_8cs" ],
    [ "Channels.cs", "_channels_8cs.html", "_channels_8cs" ],
    [ "Charity.cs", "_charity_8cs.html", "_charity_8cs" ],
    [ "Chat.cs", "_chat_8cs.html", "_chat_8cs" ],
    [ "Clips.cs", "_clips_8cs.html", "_clips_8cs" ],
    [ "Entitlements.cs", "_entitlements_8cs.html", "_entitlements_8cs" ],
    [ "EventSub.cs", "_event_sub_8cs.html", "_event_sub_8cs" ],
    [ "Extensions.cs", "_extensions_8cs.html", "_extensions_8cs" ],
    [ "Games.cs", "_games_8cs.html", "_games_8cs" ],
    [ "Goals.cs", "_goals_8cs.html", "_goals_8cs" ],
    [ "Helix.cs", "_helix_8cs.html", "_helix_8cs" ],
    [ "HypeTrain.cs", "_twitch_lib_8_api_8_helix_2_hype_train_8cs.html", "_twitch_lib_8_api_8_helix_2_hype_train_8cs" ],
    [ "Moderation.cs", "_moderation_8cs.html", "_moderation_8cs" ],
    [ "Polls.cs", "_polls_8cs.html", "_polls_8cs" ],
    [ "Predictions.cs", "_predictions_8cs.html", "_predictions_8cs" ],
    [ "Raids.cs", "_raids_8cs.html", "_raids_8cs" ],
    [ "Schedule.cs", "_schedule_8cs.html", "_schedule_8cs" ],
    [ "Search.cs", "_search_8cs.html", "_search_8cs" ],
    [ "Soundtrack.cs", "_soundtrack_8cs.html", "_soundtrack_8cs" ],
    [ "Streams.cs", "_streams_8cs.html", "_streams_8cs" ],
    [ "Subscriptions.cs", "_subscriptions_8cs.html", "_subscriptions_8cs" ],
    [ "Tags.cs", "_twitch_lib_8_api_2_twitch_lib_8_api_8_helix_2_tags_8cs.html", "_twitch_lib_8_api_2_twitch_lib_8_api_8_helix_2_tags_8cs" ],
    [ "Teams.cs", "_teams_8cs.html", "_teams_8cs" ],
    [ "Users.cs", "_users_8cs.html", "_users_8cs" ],
    [ "Videos.cs", "_videos_8cs.html", "_videos_8cs" ],
    [ "Whispers.cs", "_whispers_8cs.html", "_whispers_8cs" ]
];