var dir_1eaa0fa5b1fa124110b4d7ed295ebfed =
[
    [ "ChannelBanArgs.cs", "_channel_ban_args_8cs.html", "_channel_ban_args_8cs" ],
    [ "ChannelCharityCampaignDonateArgs.cs", "_channel_charity_campaign_donate_args_8cs.html", "_channel_charity_campaign_donate_args_8cs" ],
    [ "ChannelCheerArgs.cs", "_channel_cheer_args_8cs.html", "_channel_cheer_args_8cs" ],
    [ "ChannelFollowArgs.cs", "_channel_follow_args_8cs.html", "_channel_follow_args_8cs" ],
    [ "ChannelGoalBeginArgs.cs", "_channel_goal_begin_args_8cs.html", "_channel_goal_begin_args_8cs" ],
    [ "ChannelGoalEndArgs.cs", "_channel_goal_end_args_8cs.html", "_channel_goal_end_args_8cs" ],
    [ "ChannelGoalProgressArgs.cs", "_channel_goal_progress_args_8cs.html", "_channel_goal_progress_args_8cs" ],
    [ "ChannelHypeTrainBeginArgs.cs", "_channel_hype_train_begin_args_8cs.html", "_channel_hype_train_begin_args_8cs" ],
    [ "ChannelHypeTrainEndArgs.cs", "_channel_hype_train_end_args_8cs.html", "_channel_hype_train_end_args_8cs" ],
    [ "ChannelHypeTrainProgressArgs.cs", "_channel_hype_train_progress_args_8cs.html", "_channel_hype_train_progress_args_8cs" ],
    [ "ChannelModeratorArgs.cs", "_channel_moderator_args_8cs.html", "_channel_moderator_args_8cs" ],
    [ "ChannelPointsCustomRewardArgs.cs", "_channel_points_custom_reward_args_8cs.html", "_channel_points_custom_reward_args_8cs" ],
    [ "ChannelPointsCustomRewardRedemptionArgs.cs", "_channel_points_custom_reward_redemption_args_8cs.html", "_channel_points_custom_reward_redemption_args_8cs" ],
    [ "ChannelPollBeginArgs.cs", "_channel_poll_begin_args_8cs.html", "_channel_poll_begin_args_8cs" ],
    [ "ChannelPollEndArgs.cs", "_channel_poll_end_args_8cs.html", "_channel_poll_end_args_8cs" ],
    [ "ChannelPollProgressArgs.cs", "_channel_poll_progress_args_8cs.html", "_channel_poll_progress_args_8cs" ],
    [ "ChannelPredictionBeginArgs.cs", "_channel_prediction_begin_args_8cs.html", "_channel_prediction_begin_args_8cs" ],
    [ "ChannelPredictionEndArgs.cs", "_channel_prediction_end_args_8cs.html", "_channel_prediction_end_args_8cs" ],
    [ "ChannelPredictionLockArgs.cs", "_channel_prediction_lock_args_8cs.html", "_channel_prediction_lock_args_8cs" ],
    [ "ChannelPredictionProgressArgs.cs", "_channel_prediction_progress_args_8cs.html", "_channel_prediction_progress_args_8cs" ],
    [ "ChannelRaidArgs.cs", "_channel_raid_args_8cs.html", "_channel_raid_args_8cs" ],
    [ "ChannelSubscribeArgs.cs", "_channel_subscribe_args_8cs.html", "_channel_subscribe_args_8cs" ],
    [ "ChannelSubscriptionEndArgs.cs", "_channel_subscription_end_args_8cs.html", "_channel_subscription_end_args_8cs" ],
    [ "ChannelSubscriptionGiftArgs.cs", "_channel_subscription_gift_args_8cs.html", "_channel_subscription_gift_args_8cs" ],
    [ "ChannelSubscriptionMessageArgs.cs", "_channel_subscription_message_args_8cs.html", "_channel_subscription_message_args_8cs" ],
    [ "ChannelUnbanArgs.cs", "_channel_unban_args_8cs.html", "_channel_unban_args_8cs" ],
    [ "ChannelUpdateArgs.cs", "_channel_update_args_8cs.html", "_channel_update_args_8cs" ]
];