var dir_0a08d8770ebf2bfb077ec63b18ac4709 =
[
    [ "ChannelStateBuilder.cs", "_channel_state_builder_8cs.html", "_channel_state_builder_8cs" ],
    [ "ChatCommandBuilder.cs", "_chat_command_builder_8cs.html", "_chat_command_builder_8cs" ],
    [ "ChatMessageBuilder.cs", "_chat_message_builder_8cs.html", "_chat_message_builder_8cs" ],
    [ "CheerBadgeBuilder.cs", "_cheer_badge_builder_8cs.html", "_cheer_badge_builder_8cs" ],
    [ "CommunitySubscriptionBuilder.cs", "_community_subscription_builder_8cs.html", "_community_subscription_builder_8cs" ],
    [ "ConnectionCredentialsBuilder.cs", "_connection_credentials_builder_8cs.html", "_connection_credentials_builder_8cs" ],
    [ "EmoteBuilder.cs", "_emote_builder_8cs.html", "_emote_builder_8cs" ],
    [ "ErrorEventBuilder.cs", "_error_event_builder_8cs.html", "_error_event_builder_8cs" ],
    [ "FromIrcMessageBuilderDataObject.cs", "_from_irc_message_builder_data_object_8cs.html", "_from_irc_message_builder_data_object_8cs" ],
    [ "GiftedSubscriptionBuilder.cs", "_gifted_subscription_builder_8cs.html", "_gifted_subscription_builder_8cs" ],
    [ "IBuilder.cs", "_i_builder_8cs.html", "_i_builder_8cs" ],
    [ "IFromIrcMessageBuilder.cs", "_i_from_irc_message_builder_8cs.html", "_i_from_irc_message_builder_8cs" ],
    [ "IrcMessageBuilder.cs", "_irc_message_builder_8cs.html", "_irc_message_builder_8cs" ],
    [ "OutboundChatMessageBuilder.cs", "_outbound_chat_message_builder_8cs.html", "_outbound_chat_message_builder_8cs" ],
    [ "OutboundWhisperMessageBuilder.cs", "_outbound_whisper_message_builder_8cs.html", "_outbound_whisper_message_builder_8cs" ],
    [ "OutgoingMessageBuilder.cs", "_outgoing_message_builder_8cs.html", "_outgoing_message_builder_8cs" ],
    [ "RaidNotificationBuilder.cs", "_raid_notification_builder_8cs.html", "_raid_notification_builder_8cs" ],
    [ "ReSubscriberBuilder.cs", "_re_subscriber_builder_8cs.html", "_re_subscriber_builder_8cs" ],
    [ "RitualNewChatterBuilder.cs", "_ritual_new_chatter_builder_8cs.html", "_ritual_new_chatter_builder_8cs" ],
    [ "SentMessageBuilder.cs", "_sent_message_builder_8cs.html", "_sent_message_builder_8cs" ],
    [ "SubscriberBaseBuilder.cs", "_subscriber_base_builder_8cs.html", "_subscriber_base_builder_8cs" ],
    [ "SubscriberBuilder.cs", "_subscriber_builder_8cs.html", "_subscriber_builder_8cs" ],
    [ "TwitchLibMessageBuilder.cs", "_twitch_lib_message_builder_8cs.html", "_twitch_lib_message_builder_8cs" ],
    [ "UserBanBuilder.cs", "_user_ban_builder_8cs.html", "_user_ban_builder_8cs" ],
    [ "UserStateBuilder.cs", "_user_state_builder_8cs.html", "_user_state_builder_8cs" ],
    [ "UserTimeoutBuilder.cs", "_user_timeout_builder_8cs.html", "_user_timeout_builder_8cs" ],
    [ "WhisperCommandBuilder.cs", "_whisper_command_builder_8cs.html", "_whisper_command_builder_8cs" ],
    [ "WhisperMessageBuilder.cs", "_whisper_message_builder_8cs.html", "_whisper_message_builder_8cs" ]
];