var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements =
[
    [ "GetCodeStatus", "namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_get_code_status.html", "namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_get_code_status" ],
    [ "GetDropsEntitlements", "namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_get_drops_entitlements.html", "namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_get_drops_entitlements" ],
    [ "RedeemCode", "namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_redeem_code.html", "namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_redeem_code" ],
    [ "UpdateDropsEntitlements", "namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_update_drops_entitlements.html", "namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_update_drops_entitlements" ],
    [ "Status", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_status.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_status" ]
];