var namespace_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args =
[
    [ "Channel", "namespace_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel.html", "namespace_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel" ],
    [ "Stream", "namespace_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_stream.html", "namespace_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_stream" ],
    [ "User", "namespace_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_user.html", "namespace_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_user" ],
    [ "ErrorOccuredArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_error_occured_args.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_error_occured_args" ],
    [ "RevocationArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_revocation_args.html", null ],
    [ "TwitchLibEventSubEventArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_twitch_lib_event_sub_event_args.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_twitch_lib_event_sub_event_args" ],
    [ "WebsocketConnectedArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_websocket_connected_args.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_websocket_connected_args" ],
    [ "WebsocketDisconnectedArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_websocket_disconnected_args.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_websocket_disconnected_args" ]
];