var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channel_points_1_1_update_custom_reward =
[
    [ "UpdateCustomRewardRequest", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channel_points_1_1_update_custom_reward_1_1_update_custom_reward_request.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channel_points_1_1_update_custom_reward_1_1_update_custom_reward_request" ],
    [ "UpdateCustomRewardResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channel_points_1_1_update_custom_reward_1_1_update_custom_reward_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channel_points_1_1_update_custom_reward_1_1_update_custom_reward_response" ]
];