var namespace_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel =
[
    [ "ChannelBanArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_ban_args.html", null ],
    [ "ChannelCharityCampaignDonateArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_charity_campaign_donate_args.html", null ],
    [ "ChannelCheerArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_cheer_args.html", null ],
    [ "ChannelFollowArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_follow_args.html", null ],
    [ "ChannelGoalBeginArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_goal_begin_args.html", null ],
    [ "ChannelGoalEndArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_goal_end_args.html", null ],
    [ "ChannelGoalProgressArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_goal_progress_args.html", null ],
    [ "ChannelHypeTrainBeginArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_hype_train_begin_args.html", null ],
    [ "ChannelHypeTrainEndArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_hype_train_end_args.html", null ],
    [ "ChannelHypeTrainProgressArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_hype_train_progress_args.html", null ],
    [ "ChannelModeratorArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_moderator_args.html", null ],
    [ "ChannelPointsCustomRewardArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_points_custom_reward_args.html", null ],
    [ "ChannelPointsCustomRewardRedemptionArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_poe0d9588bfaa77e3a94be574ee4d2a444.html", null ],
    [ "ChannelPollBeginArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_poll_begin_args.html", null ],
    [ "ChannelPollEndArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_poll_end_args.html", null ],
    [ "ChannelPollProgressArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_poll_progress_args.html", null ],
    [ "ChannelPredictionBeginArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_prediction_begin_args.html", null ],
    [ "ChannelPredictionEndArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_prediction_end_args.html", null ],
    [ "ChannelPredictionLockArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_prediction_lock_args.html", null ],
    [ "ChannelPredictionProgressArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_prediction_progress_args.html", null ],
    [ "ChannelRaidArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_raid_args.html", null ],
    [ "ChannelSubscribeArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_subscribe_args.html", null ],
    [ "ChannelSubscriptionEndArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_subscription_end_args.html", null ],
    [ "ChannelSubscriptionGiftArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_subscription_gift_args.html", null ],
    [ "ChannelSubscriptionMessageArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_subscription_message_args.html", null ],
    [ "ChannelUnbanArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_unban_args.html", null ],
    [ "ChannelUpdateArgs", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_event_args_1_1_channel_1_1_channel_update_args.html", null ]
];