var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_chat_settings =
[
    [ "ChatSettings", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_chat_settings_1_1_chat_settings.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_chat_settings_1_1_chat_settings" ],
    [ "ChatSettingsResponseModel", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_chat_settings_1_1_chat_settings_response_model.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_chat_settings_1_1_chat_settings_response_model" ],
    [ "GetChatSettingsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_chat_settings_1_1_get_chat_settings_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_chat_settings_1_1_get_chat_settings_response" ],
    [ "UpdateChatSettingsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_chat_settings_1_1_update_chat_settings_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_chat_settings_1_1_update_chat_settings_response" ],
    [ "UpdateChatSettingsResponseModel", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_chat_settings_1_1_update_chat_settings_response_model.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_chat_1_1_chat_settings_1_1_update_chat_settings_response_model" ]
];