var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_editors =
[
    [ "ChannelEditor", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_editors_1_1_channel_editor.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_editors_1_1_channel_editor" ],
    [ "GetChannelEditorsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_editors_1_1_get_channel_editors_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_editors_1_1_get_channel_editors_response" ]
];