var namespace_twitch_lib_1_1_api_1_1_services_1_1_events_1_1_live_stream_monitor =
[
    [ "OnStreamOfflineArgs", "class_twitch_lib_1_1_api_1_1_services_1_1_events_1_1_live_stream_monitor_1_1_on_stream_offline_args.html", "class_twitch_lib_1_1_api_1_1_services_1_1_events_1_1_live_stream_monitor_1_1_on_stream_offline_args" ],
    [ "OnStreamOnlineArgs", "class_twitch_lib_1_1_api_1_1_services_1_1_events_1_1_live_stream_monitor_1_1_on_stream_online_args.html", "class_twitch_lib_1_1_api_1_1_services_1_1_events_1_1_live_stream_monitor_1_1_on_stream_online_args" ],
    [ "OnStreamUpdateArgs", "class_twitch_lib_1_1_api_1_1_services_1_1_events_1_1_live_stream_monitor_1_1_on_stream_update_args.html", "class_twitch_lib_1_1_api_1_1_services_1_1_events_1_1_live_stream_monitor_1_1_on_stream_update_args" ]
];