var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_bits_1_1_extension_bits_products =
[
    [ "Cost", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_bits_1_1_extension_bits_products_1_1_cost.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_bits_1_1_extension_bits_products_1_1_cost" ],
    [ "ExtensionBitsProduct", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_bits_1_1_extension_bits_products_1_1_extension_bits_product.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_bits_1_1_extension_bits_products_1_1_extension_bits_product" ],
    [ "GetExtensionBitsProductsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_bits_1_1_extension_bits_products_1_1_get_extension_bits_products_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_bits_1_1_extension_bits_products_1_1_get_extension_bits_products_response" ],
    [ "UpdateExtensionBitsProductResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_bits_1_1_extension_bits_products_1_1_update_extension_bits_product_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_bits_1_1_extension_bits_products_1_1_update_extension_bits_product_response" ]
];