var namespace_twitch_lib_1_1_api_1_1_third_party_1_1_username_change =
[
    [ "UsernameChangeListing", "class_twitch_lib_1_1_api_1_1_third_party_1_1_username_change_1_1_username_change_listing.html", "class_twitch_lib_1_1_api_1_1_third_party_1_1_username_change_1_1_username_change_listing" ],
    [ "UsernameChangeResponse", "class_twitch_lib_1_1_api_1_1_third_party_1_1_username_change_1_1_username_change_response.html", "class_twitch_lib_1_1_api_1_1_third_party_1_1_username_change_1_1_username_change_response" ]
];