var namespace_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_handler =
[
    [ "INotificationHandler", "interface_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_handler_1_1_i_notification_handler.html", "interface_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_handler_1_1_i_notification_handler" ]
];