var namespace_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_charity =
[
    [ "ChannelCharityCampaignDonateHandler", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_charity_1_1_channel_charity_campaign_donate_handler.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_charity_1_1_channel_charity_campaign_donate_handler" ]
];