var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_streams_1_1_create_stream_marker =
[
    [ "CreatedMarker", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_streams_1_1_create_stream_marker_1_1_created_marker.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_streams_1_1_create_stream_marker_1_1_created_marker" ],
    [ "CreateStreamMarkerRequest", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_streams_1_1_create_stream_marker_1_1_create_stream_marker_request.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_streams_1_1_create_stream_marker_1_1_create_stream_marker_request" ],
    [ "CreateStreamMarkerResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_streams_1_1_create_stream_marker_1_1_create_stream_marker_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_streams_1_1_create_stream_marker_1_1_create_stream_marker_response" ]
];