var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_v_i_ps =
[
    [ "ChannelVIPsResponseModel", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_v_i_ps_1_1_channel_v_i_ps_response_model.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_v_i_ps_1_1_channel_v_i_ps_response_model" ],
    [ "GetChannelVIPsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_v_i_ps_1_1_get_channel_v_i_ps_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channels_1_1_get_channel_v_i_ps_1_1_get_channel_v_i_ps_response" ]
];