var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_charity =
[
    [ "GetCharityCampaign", "namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_charity_1_1_get_charity_campaign.html", "namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_charity_1_1_get_charity_campaign" ]
];