var namespace_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_user =
[
    [ "UserUpdateHandler", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_user_1_1_user_update_handler.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_user_1_1_user_update_handler" ]
];