var namespace_twitch_lib_1_1_client_1_1_models_1_1_builders =
[
    [ "ChannelStateBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_channel_state_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_channel_state_builder" ],
    [ "ChatCommandBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_chat_command_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_chat_command_builder" ],
    [ "ChatMessageBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_chat_message_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_chat_message_builder" ],
    [ "CheerBadgeBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_cheer_badge_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_cheer_badge_builder" ],
    [ "CommunitySubscriptionBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_community_subscription_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_community_subscription_builder" ],
    [ "ConnectionCredentialsBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_connection_credentials_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_connection_credentials_builder" ],
    [ "EmoteBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_emote_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_emote_builder" ],
    [ "ErrorEventBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_error_event_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_error_event_builder" ],
    [ "FromIrcMessageBuilderDataObject", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_from_irc_message_builder_data_object.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_from_irc_message_builder_data_object" ],
    [ "GiftedSubscriptionBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_gifted_subscription_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_gifted_subscription_builder" ],
    [ "IBuilder", "interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html", "interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder" ],
    [ "IFromIrcMessageBuilder", "interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_from_irc_message_builder.html", "interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_from_irc_message_builder" ],
    [ "IrcMessageBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_irc_message_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_irc_message_builder" ],
    [ "OutboundChatMessageBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_outbound_chat_message_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_outbound_chat_message_builder" ],
    [ "OutboundWhisperMessageBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_outbound_whisper_message_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_outbound_whisper_message_builder" ],
    [ "OutgoingMessageBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_outgoing_message_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_outgoing_message_builder" ],
    [ "RaidNotificationBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_raid_notification_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_raid_notification_builder" ],
    [ "ReSubscriberBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_re_subscriber_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_re_subscriber_builder" ],
    [ "RitualNewChatterBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_ritual_new_chatter_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_ritual_new_chatter_builder" ],
    [ "SentMessageBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_sent_message_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_sent_message_builder" ],
    [ "SubscriberBaseBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_subscriber_base_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_subscriber_base_builder" ],
    [ "SubscriberBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_subscriber_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_subscriber_builder" ],
    [ "TwitchLibMessageBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_twitch_lib_message_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_twitch_lib_message_builder" ],
    [ "UserBanBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_user_ban_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_user_ban_builder" ],
    [ "UserStateBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_user_state_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_user_state_builder" ],
    [ "UserTimeoutBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_user_timeout_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_user_timeout_builder" ],
    [ "WhisperCommandBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_whisper_command_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_whisper_command_builder" ],
    [ "WhisperMessageBuilder", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_whisper_message_builder.html", "class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_whisper_message_builder" ]
];