var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_get_banned_events =
[
    [ "BannedEvent", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_get_banned_events_1_1_banned_event.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_get_banned_events_1_1_banned_event" ],
    [ "EventData", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_get_banned_events_1_1_event_data.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_get_banned_events_1_1_event_data" ],
    [ "GetBannedEventsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_get_banned_events_1_1_get_banned_events_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_get_banned_events_1_1_get_banned_events_response" ]
];