var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_get_banned_users =
[
    [ "BannedUserEvent", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_get_banned_users_1_1_banned_user_event.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_get_banned_users_1_1_banned_user_event" ],
    [ "GetBannedUsersResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_get_banned_users_1_1_get_banned_users_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_get_banned_users_1_1_get_banned_users_response" ]
];