var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_check_auto_mod_status =
[
    [ "Request", "namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_check_auto_mod_status_1_1_request.html", "namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_check_auto_mod_status_1_1_request" ],
    [ "AutoModResult", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_check_auto_mod_status_1_1_auto_mod_result.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_check_auto_mod_status_1_1_auto_mod_result" ],
    [ "CheckAutoModStatusResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_check_auto_mod_status_1_1_check_auto_mod_status_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_check_auto_mod_status_1_1_check_auto_mod_status_response" ],
    [ "Message", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_check_auto_mod_status_1_1_message.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_check_auto_mod_status_1_1_message" ]
];