var namespace_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_cheers =
[
    [ "ChannelCheerHandler", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_cheers_1_1_channel_cheer_handler.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_cheers_1_1_channel_cheer_handler" ]
];