var namespace_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_stream =
[
    [ "StreamOfflineHandler", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_stream_1_1_stream_offline_handler.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_stream_1_1_stream_offline_handler" ],
    [ "StreamOnlineHandler", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_stream_1_1_stream_online_handler.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_stream_1_1_stream_online_handler" ]
];