var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channel_points_1_1_create_custom_reward =
[
    [ "CreateCustomRewardsRequest", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channel_points_1_1_create_custom_reward_1_1_create_custom_rewards_request.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channel_points_1_1_create_custom_reward_1_1_create_custom_rewards_request" ],
    [ "CreateCustomRewardsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channel_points_1_1_create_custom_reward_1_1_create_custom_rewards_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channel_points_1_1_create_custom_reward_1_1_create_custom_rewards_response" ]
];