var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_streams_1_1_get_followed_streams =
[
    [ "GetFollowedStreamsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_streams_1_1_get_followed_streams_1_1_get_followed_streams_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_streams_1_1_get_followed_streams_1_1_get_followed_streams_response" ],
    [ "Stream", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_streams_1_1_get_followed_streams_1_1_stream.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_streams_1_1_get_followed_streams_1_1_stream" ]
];