var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_redeem_code =
[
    [ "RedeemCodeResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_redeem_code_1_1_redeem_code_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_redeem_code_1_1_redeem_code_response" ]
];