var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_ads =
[
    [ "StartCommercialRequest", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_ads_1_1_start_commercial_request.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_ads_1_1_start_commercial_request" ],
    [ "StartCommercialResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_ads_1_1_start_commercial_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_ads_1_1_start_commercial_response" ]
];