var namespace_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_goals =
[
    [ "ChannelGoalBeginHandler", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_goals_1_1_channel_goal_begin_handler.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_goals_1_1_channel_goal_begin_handler" ],
    [ "ChannelGoalEndHandler", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_goals_1_1_channel_goal_end_handler.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_goals_1_1_channel_goal_end_handler" ],
    [ "ChannelGoalProgressHandler", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_goals_1_1_channel_goal_progress_handler.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_handler_1_1_channel_1_1_goals_1_1_channel_goal_progress_handler" ]
];