var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_users_1_1_get_user_extensions =
[
    [ "GetUserExtensionsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_users_1_1_get_user_extensions_1_1_get_user_extensions_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_users_1_1_get_user_extensions_1_1_get_user_extensions_response" ]
];