var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_analytics =
[
    [ "ExtensionAnalytics", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_analytics_1_1_extension_analytics.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_analytics_1_1_extension_analytics" ],
    [ "GameAnalytics", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_analytics_1_1_game_analytics.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_analytics_1_1_game_analytics" ],
    [ "GetExtensionAnalyticsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_analytics_1_1_get_extension_analytics_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_analytics_1_1_get_extension_analytics_response" ],
    [ "GetGameAnalyticsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_analytics_1_1_get_game_analytics_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_analytics_1_1_get_game_analytics_response" ]
];