var namespace_twitch_lib_1_1_event_sub_1_1_websockets_1_1_example_1_1_net_standard =
[
    [ "WebsocketHostedService", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_example_1_1_net_standard_1_1_websocket_hosted_service.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_example_1_1_net_standard_1_1_websocket_hosted_service" ]
];