var namespace_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_naming_policies =
[
    [ "SnakeCaseNamingPolicy", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_naming_policies_1_1_snake_case_naming_policy.html", "class_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_naming_policies_1_1_snake_case_naming_policy" ]
];