var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_event_sub =
[
    [ "CreateEventSubSubscriptionResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_event_sub_1_1_create_event_sub_subscription_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_event_sub_1_1_create_event_sub_subscription_response" ],
    [ "EventSubSubscription", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_event_sub_1_1_event_sub_subscription.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_event_sub_1_1_event_sub_subscription" ],
    [ "EventSubTransport", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_event_sub_1_1_event_sub_transport.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_event_sub_1_1_event_sub_transport" ],
    [ "GetEventSubSubscriptionsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_event_sub_1_1_get_event_sub_subscriptions_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_event_sub_1_1_get_event_sub_subscriptions_response" ]
];