var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_charity_1_1_get_charity_campaign =
[
    [ "Amount", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_charity_1_1_get_charity_campaign_1_1_amount.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_charity_1_1_get_charity_campaign_1_1_amount" ],
    [ "CharityCampaignResponseModel", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_charity_1_1_get_charity_campaign_1_1_charity_campaign_response_model.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_charity_1_1_get_charity_campaign_1_1_charity_campaign_response_model" ],
    [ "GetCharityCampaignResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_charity_1_1_get_charity_campaign_1_1_get_charity_campaign_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_charity_1_1_get_charity_campaign_1_1_get_charity_campaign_response" ]
];