var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_get_drops_entitlements =
[
    [ "DropsEntitlement", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_get_drops_entitlements_1_1_drops_entitlement.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_get_drops_entitlements_1_1_drops_entitlement" ],
    [ "GetDropsEntitlementsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_get_drops_entitlements_1_1_get_drops_entitlements_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_entitlements_1_1_get_drops_entitlements_1_1_get_drops_entitlements_response" ]
];