var namespace_twitch_lib_1_1_api_1_1_helix =
[
    [ "Models", "namespace_twitch_lib_1_1_api_1_1_helix_1_1_models.html", "namespace_twitch_lib_1_1_api_1_1_helix_1_1_models" ],
    [ "Ads", "class_twitch_lib_1_1_api_1_1_helix_1_1_ads.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_ads" ],
    [ "Analytics", "class_twitch_lib_1_1_api_1_1_helix_1_1_analytics.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_analytics" ],
    [ "Bits", "class_twitch_lib_1_1_api_1_1_helix_1_1_bits.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_bits" ],
    [ "ChannelPoints", "class_twitch_lib_1_1_api_1_1_helix_1_1_channel_points.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_channel_points" ],
    [ "Channels", "class_twitch_lib_1_1_api_1_1_helix_1_1_channels.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_channels" ],
    [ "Charity", "class_twitch_lib_1_1_api_1_1_helix_1_1_charity.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_charity" ],
    [ "Chat", "class_twitch_lib_1_1_api_1_1_helix_1_1_chat.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_chat" ],
    [ "Clips", "class_twitch_lib_1_1_api_1_1_helix_1_1_clips.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_clips" ],
    [ "Entitlements", "class_twitch_lib_1_1_api_1_1_helix_1_1_entitlements.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_entitlements" ],
    [ "EventSub", "class_twitch_lib_1_1_api_1_1_helix_1_1_event_sub.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_event_sub" ],
    [ "Extensions", "class_twitch_lib_1_1_api_1_1_helix_1_1_extensions.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_extensions" ],
    [ "Games", "class_twitch_lib_1_1_api_1_1_helix_1_1_games.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_games" ],
    [ "Goals", "class_twitch_lib_1_1_api_1_1_helix_1_1_goals.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_goals" ],
    [ "Helix", "class_twitch_lib_1_1_api_1_1_helix_1_1_helix.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_helix" ],
    [ "HypeTrain", "class_twitch_lib_1_1_api_1_1_helix_1_1_hype_train.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_hype_train" ],
    [ "Moderation", "class_twitch_lib_1_1_api_1_1_helix_1_1_moderation.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_moderation" ],
    [ "Polls", "class_twitch_lib_1_1_api_1_1_helix_1_1_polls.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_polls" ],
    [ "Predictions", "class_twitch_lib_1_1_api_1_1_helix_1_1_predictions.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_predictions" ],
    [ "Raids", "class_twitch_lib_1_1_api_1_1_helix_1_1_raids.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_raids" ],
    [ "Schedule", "class_twitch_lib_1_1_api_1_1_helix_1_1_schedule.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_schedule" ],
    [ "Search", "class_twitch_lib_1_1_api_1_1_helix_1_1_search.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_search" ],
    [ "Soundtrack", "class_twitch_lib_1_1_api_1_1_helix_1_1_soundtrack.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_soundtrack" ],
    [ "Streams", "class_twitch_lib_1_1_api_1_1_helix_1_1_streams.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_streams" ],
    [ "Subscriptions", "class_twitch_lib_1_1_api_1_1_helix_1_1_subscriptions.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_subscriptions" ],
    [ "Tags", "class_twitch_lib_1_1_api_1_1_helix_1_1_tags.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_tags" ],
    [ "Teams", "class_twitch_lib_1_1_api_1_1_helix_1_1_teams.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_teams" ],
    [ "Users", "class_twitch_lib_1_1_api_1_1_helix_1_1_users.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_users" ],
    [ "Videos", "class_twitch_lib_1_1_api_1_1_helix_1_1_videos.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_videos" ],
    [ "Whispers", "class_twitch_lib_1_1_api_1_1_helix_1_1_whispers.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_whispers" ]
];