var namespace_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_automod_settings =
[
    [ "AutomodSettings", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_automod_settings_1_1_automod_settings.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_automod_settings_1_1_automod_settings" ],
    [ "AutomodSettingsResponseModel", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_automod_settings_1_1_automod_settings_response_model.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_automod_settings_1_1_automod_settings_response_model" ],
    [ "GetAutomodSettingsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_automod_settings_1_1_get_automod_settings_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_automod_settings_1_1_get_automod_settings_response" ],
    [ "UpdateAutomodSettingsResponse", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_automod_settings_1_1_update_automod_settings_response.html", "class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_moderation_1_1_automod_settings_1_1_update_automod_settings_response" ]
];