var searchData=
[
  ['iapisettings_0',['IApiSettings',['../interface_twitch_lib_1_1_api_1_1_core_1_1_interfaces_1_1_i_api_settings.html',1,'TwitchLib::Api::Core::Interfaces']]],
  ['iawaitableconstraint_1',['IAwaitableConstraint',['../interface_twitch_lib_1_1_api_1_1_core_1_1_interfaces_1_1_i_awaitable_constraint.html',1,'TwitchLib::Api::Core::Interfaces']]],
  ['ibuilder_2',['IBuilder',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20channelstate_20_3e_3',['IBuilder&lt; ChannelState &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20chatcommand_20_3e_4',['IBuilder&lt; ChatCommand &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20chatmessage_20_3e_5',['IBuilder&lt; ChatMessage &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20cheerbadge_20_3e_6',['IBuilder&lt; CheerBadge &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20connectioncredentials_20_3e_7',['IBuilder&lt; ConnectionCredentials &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20emote_20_3e_8',['IBuilder&lt; Emote &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20errorevent_20_3e_9',['IBuilder&lt; ErrorEvent &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20giftedsubscription_20_3e_10',['IBuilder&lt; GiftedSubscription &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20ircmessage_20_3e_11',['IBuilder&lt; IrcMessage &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20outboundchatmessage_20_3e_12',['IBuilder&lt; OutboundChatMessage &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20outboundwhispermessage_20_3e_13',['IBuilder&lt; OutboundWhisperMessage &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20outgoingmessage_20_3e_14',['IBuilder&lt; OutgoingMessage &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20raidnotification_20_3e_15',['IBuilder&lt; RaidNotification &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20resubscriber_20_3e_16',['IBuilder&lt; ReSubscriber &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20sentmessage_20_3e_17',['IBuilder&lt; SentMessage &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20subscriber_20_3e_18',['IBuilder&lt; Subscriber &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20subscriberbase_20_3e_19',['IBuilder&lt; SubscriberBase &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20twitchlibmessage_20_3e_20',['IBuilder&lt; TwitchLibMessage &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20userban_20_3e_21',['IBuilder&lt; UserBan &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20userstate_20_3e_22',['IBuilder&lt; UserState &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20usertimeout_20_3e_23',['IBuilder&lt; UserTimeout &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20whispercommand_20_3e_24',['IBuilder&lt; WhisperCommand &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ibuilder_3c_20whispermessage_20_3e_25',['IBuilder&lt; WhisperMessage &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['iconurls_26',['IconUrls',['../class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_extensions_1_1_released_extensions_1_1_icon_urls.html',1,'TwitchLib::Api::Helix::Models::Extensions::ReleasedExtensions']]],
  ['iextractor_27',['IExtractor',['../interface_twitch_lib_1_1_client_1_1_models_1_1_extractors_1_1_i_extractor.html',1,'TwitchLib::Client::Models::Extractors']]],
  ['ifollow_28',['IFollow',['../interface_twitch_lib_1_1_api_1_1_core_1_1_interfaces_1_1_i_follow.html',1,'TwitchLib::Api::Core::Interfaces']]],
  ['ifollows_29',['IFollows',['../interface_twitch_lib_1_1_api_1_1_core_1_1_interfaces_1_1_i_follows.html',1,'TwitchLib::Api::Core::Interfaces']]],
  ['ifromircmessagebuilder_30',['IFromIrcMessageBuilder',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_from_irc_message_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ifromircmessagebuilder_3c_20channelstate_20_3e_31',['IFromIrcMessageBuilder&lt; ChannelState &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_from_irc_message_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ifromircmessagebuilder_3c_20communitysubscription_20_3e_32',['IFromIrcMessageBuilder&lt; CommunitySubscription &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_from_irc_message_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ifromircmessagebuilder_3c_20giftedsubscription_20_3e_33',['IFromIrcMessageBuilder&lt; GiftedSubscription &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_from_irc_message_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ifromircmessagebuilder_3c_20raidnotification_20_3e_34',['IFromIrcMessageBuilder&lt; RaidNotification &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_from_irc_message_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ifromircmessagebuilder_3c_20resubscriber_20_3e_35',['IFromIrcMessageBuilder&lt; ReSubscriber &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_from_irc_message_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ifromircmessagebuilder_3c_20ritualnewchatter_20_3e_36',['IFromIrcMessageBuilder&lt; RitualNewChatter &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_from_irc_message_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ifromircmessagebuilder_3c_20subscriber_20_3e_37',['IFromIrcMessageBuilder&lt; Subscriber &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_from_irc_message_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ifromircmessagebuilder_3c_20userban_20_3e_38',['IFromIrcMessageBuilder&lt; UserBan &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_from_irc_message_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ifromircmessagebuilder_3c_20userstate_20_3e_39',['IFromIrcMessageBuilder&lt; UserState &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_from_irc_message_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ifromircmessagebuilder_3c_20usertimeout_20_3e_40',['IFromIrcMessageBuilder&lt; UserTimeout &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_from_irc_message_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ifromircmessagebuilder_3c_20whispermessage_20_3e_41',['IFromIrcMessageBuilder&lt; WhisperMessage &gt;',['../interface_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_i_from_irc_message_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['ihttpcallhandler_42',['IHttpCallHandler',['../interface_twitch_lib_1_1_api_1_1_core_1_1_interfaces_1_1_i_http_call_handler.html',1,'TwitchLib::Api::Core::Interfaces']]],
  ['illegalassignmentexception_43',['IllegalAssignmentException',['../class_twitch_lib_1_1_client_1_1_exceptions_1_1_illegal_assignment_exception.html',1,'TwitchLib::Client::Exceptions']]],
  ['image_44',['Image',['../class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_channel_points_1_1_image.html',1,'TwitchLib::Api::Helix::Models::ChannelPoints']]],
  ['imagelist_45',['ImageList',['../class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_bits_1_1_image_list.html',1,'TwitchLib::Api::Helix::Models::Bits']]],
  ['images_46',['Images',['../class_twitch_lib_1_1_api_1_1_helix_1_1_models_1_1_bits_1_1_images.html',1,'TwitchLib::Api::Helix::Models::Bits']]],
  ['inotificationhandler_47',['INotificationHandler',['../interface_twitch_lib_1_1_event_sub_1_1_websockets_1_1_core_1_1_handler_1_1_i_notification_handler.html',1,'TwitchLib::EventSub::Websockets::Core::Handler']]],
  ['internalservererrorexception_48',['InternalServerErrorException',['../class_twitch_lib_1_1_api_1_1_core_1_1_exceptions_1_1_internal_server_error_exception.html',1,'TwitchLib::Api::Core::Exceptions']]],
  ['invalidcredentialexception_49',['InvalidCredentialException',['../class_twitch_lib_1_1_api_1_1_core_1_1_exceptions_1_1_invalid_credential_exception.html',1,'TwitchLib::Api::Core::Exceptions']]],
  ['invalidparameterexception_50',['InvalidParameterException',['../class_twitch_lib_1_1_client_1_1_exceptions_1_1_invalid_parameter_exception.html',1,'TwitchLib::Client::Exceptions']]],
  ['iratelimiter_51',['IRateLimiter',['../interface_twitch_lib_1_1_api_1_1_core_1_1_interfaces_1_1_i_rate_limiter.html',1,'TwitchLib::Api::Core::Interfaces']]],
  ['ircmessage_52',['IrcMessage',['../class_twitch_lib_1_1_client_1_1_models_1_1_internal_1_1_irc_message.html',1,'TwitchLib::Client::Models::Internal']]],
  ['ircmessagebuilder_53',['IrcMessageBuilder',['../class_twitch_lib_1_1_client_1_1_models_1_1_builders_1_1_irc_message_builder.html',1,'TwitchLib::Client::Models::Builders']]],
  ['itime_54',['ITime',['../interface_twitch_lib_1_1_api_1_1_core_1_1_interfaces_1_1_i_time.html',1,'TwitchLib::Api::Core::Interfaces']]],
  ['itwitchapi_55',['ITwitchAPI',['../interface_twitch_lib_1_1_api_1_1_interfaces_1_1_i_twitch_a_p_i.html',1,'TwitchLib::Api::Interfaces']]],
  ['itwitchclient_56',['ITwitchClient',['../interface_twitch_lib_1_1_client_1_1_interfaces_1_1_i_twitch_client.html',1,'TwitchLib::Client::Interfaces']]],
  ['itwitchpubsub_57',['ITwitchPubSub',['../interface_twitch_lib_1_1_pub_sub_1_1_interfaces_1_1_i_twitch_pub_sub.html',1,'TwitchLib::PubSub::Interfaces']]],
  ['iuser_58',['IUser',['../interface_twitch_lib_1_1_api_1_1_core_1_1_interfaces_1_1_i_user.html',1,'TwitchLib::Api::Core::Interfaces']]]
];
