var searchData=
[
  ['schedule_2ecs_0',['Schedule.cs',['../_schedule_8cs.html',1,'']]],
  ['search_2ecs_1',['Search.cs',['../_search_8cs.html',1,'']]],
  ['searchcategoriesresponse_2ecs_2',['SearchCategoriesResponse.cs',['../_search_categories_response_8cs.html',1,'']]],
  ['searchchannelsresponse_2ecs_3',['SearchChannelsResponse.cs',['../_search_channels_response_8cs.html',1,'']]],
  ['segment_2ecs_4',['Segment.cs',['../_segment_8cs.html',1,'']]],
  ['sender_2ecs_5',['Sender.cs',['../_sender_8cs.html',1,'']]],
  ['sendreceivedirection_2ecs_6',['SendReceiveDirection.cs',['../_send_receive_direction_8cs.html',1,'']]],
  ['sentmessage_2ecs_7',['SentMessage.cs',['../_sent_message_8cs.html',1,'']]],
  ['sentmessagebuilder_2ecs_8',['SentMessageBuilder.cs',['../_sent_message_builder_8cs.html',1,'']]],
  ['servicecollectionextensions_2ecs_9',['ServiceCollectionExtensions.cs',['../_service_collection_extensions_8cs.html',1,'']]],
  ['servicetimer_2ecs_10',['ServiceTimer.cs',['../_service_timer_8cs.html',1,'']]],
  ['slowmodeext_2ecs_11',['SlowModeExt.cs',['../_slow_mode_ext_8cs.html',1,'']]],
  ['snakecasenamingpolicy_2ecs_12',['SnakeCaseNamingPolicy.cs',['../_snake_case_naming_policy_8cs.html',1,'']]],
  ['soundtrack_2ecs_13',['Soundtrack.cs',['../_soundtrack_8cs.html',1,'']]],
  ['source_2ecs_14',['Source.cs',['../_source_8cs.html',1,'']]],
  ['startcommercialrequest_2ecs_15',['StartCommercialRequest.cs',['../_start_commercial_request_8cs.html',1,'']]],
  ['startcommercialresponse_2ecs_16',['StartCommercialResponse.cs',['../_start_commercial_response_8cs.html',1,'']]],
  ['startraidresponse_2ecs_17',['StartRaidResponse.cs',['../_start_raid_response_8cs.html',1,'']]],
  ['stats_2ecs_18',['Stats.cs',['../_stats_8cs.html',1,'']]],
  ['statsresponse_2ecs_19',['StatsResponse.cs',['../_stats_response_8cs.html',1,'']]],
  ['status_2ecs_20',['Status.cs',['../_status_8cs.html',1,'']]],
  ['stream_2ecs_21',['Stream.cs',['../_get_streams_2_stream_8cs.html',1,'(Global Namespace)'],['../_get_followed_streams_2_stream_8cs.html',1,'(Global Namespace)']]],
  ['streamkey_2ecs_22',['StreamKey.cs',['../_stream_key_8cs.html',1,'']]],
  ['streamofflineargs_2ecs_23',['StreamOfflineArgs.cs',['../_stream_offline_args_8cs.html',1,'']]],
  ['streamofflinehandler_2ecs_24',['StreamOfflineHandler.cs',['../_stream_offline_handler_8cs.html',1,'']]],
  ['streamonlineargs_2ecs_25',['StreamOnlineArgs.cs',['../_stream_online_args_8cs.html',1,'']]],
  ['streamonlinehandler_2ecs_26',['StreamOnlineHandler.cs',['../_stream_online_handler_8cs.html',1,'']]],
  ['streams_2ecs_27',['Streams.cs',['../_streams_8cs.html',1,'']]],
  ['stringenum_2ecs_28',['StringEnum.cs',['../_twitch_lib_8_client_2_twitch_lib_8_client_8_enums_2_string_enum_8cs.html',1,'(Global Namespace)'],['../_twitch_lib_8_api_2_twitch_lib_8_api_8_core_8_enums_2_string_enum_8cs.html',1,'(Global Namespace)']]],
  ['stringextensions_2ecs_29',['StringExtensions.cs',['../_string_extensions_8cs.html',1,'']]],
  ['submessage_2ecs_30',['SubMessage.cs',['../_sub_message_8cs.html',1,'']]],
  ['subscriber_2ecs_31',['Subscriber.cs',['../_subscriber_8cs.html',1,'']]],
  ['subscriberbase_2ecs_32',['SubscriberBase.cs',['../_subscriber_base_8cs.html',1,'']]],
  ['subscriberbasebuilder_2ecs_33',['SubscriberBaseBuilder.cs',['../_subscriber_base_builder_8cs.html',1,'']]],
  ['subscriberbuilder_2ecs_34',['SubscriberBuilder.cs',['../_subscriber_builder_8cs.html',1,'']]],
  ['subscribersonly_2ecs_35',['SubscribersOnly.cs',['../_subscribers_only_8cs.html',1,'']]],
  ['subscription_2ecs_36',['Subscription.cs',['../_subscription_8cs.html',1,'']]],
  ['subscriptionplanenum_2ecs_37',['SubscriptionPlanEnum.cs',['../_twitch_lib_8_client_2_twitch_lib_8_client_8_enums_2_subscription_plan_enum_8cs.html',1,'(Global Namespace)'],['../_twitch_lib_8_pub_sub_2_twitch_lib_8_pub_sub_2_enums_2_subscription_plan_enum_8cs.html',1,'(Global Namespace)']]],
  ['subscriptions_2ecs_38',['Subscriptions.cs',['../_subscriptions_8cs.html',1,'']]]
];
